CREATE TABLE TB_DOMICILIO_BANCARIO(
ID_DOMICILIO_BANCARIO int PRIMARY KEY,
CODIGO_BANCO int,
NUM_AGENCIA int,
NUM_CONTA_CORRENTE varchar(14)
)

CREATE TABLE REMESSA(

)

CREATE TABLE TB_LANCAMENTO(
ID_LANCAMENTO int PRIMARY KEY,
ID_DOMICILIO_BANCARIO int,
CODIGO_BANCO int,
NUM_AGENCIA int,
NUM_CONTA_CORRENTE varchar(14)
)

CREATE TABLE REMESSA_LANCAMENTO(
)