CREATE TABLE TB_DOMICILIO_BANCARIO(
ID_DOMICILIO_BANCARIO int PRIMARY KEY,
CODIGO_BANCO int,
NUM_AGENCIA int,
NUM_CONTA_CORRENTE varchar(14)
)

CREATE TABLE TB_REMESSA(
ID_REMESSA int PRIMARY KEY,
ID_DOMICILIO_BANCARIO int,
NUM_REMESSA_BANCO int,
NOME_SITUACAO_REMESSA varchar(50),
NOME_TIPO_OPERACAO varchar(50)
)

CREATE TABLE TB_LANCAMENTO(
ID_LANCAMENTO int PRIMARY KEY,
ID_REMESSA int,
DT_EFETIVA_LANCAMENTO date,
DT_LANCAMENTO_CONTA_CORRENTE_CLIENTE date,
NUM_EVENTO int,
DESC_GRUPO_PAGAMENTO varchar(50),
ID_UNICO_LEGADO int,
NOME_BANCO varchar(50),
QTD_LANCAMENTO_REMESSA int,
NUM_RAIZ_CNPJ varchar(8),
NUM_SUFIX_CNPJ varchar(4),
VALOR_LANCAMENTO_REMESSA decimal(10,2)
)

CREATE SEQUENCE SQ_DOMICILIO_BANCARIO
START WITH 1
MINVALUE 1
INCREMENT BY 1
NO MAXVALUE
NO CACHE
NOCYCLE

CREATE SEQUENCE SQ_REMESSA
START WITH 1
MINVALUE 1
INCREMENT BY 1
NO MAXVALUE
NO CACHE
NOCYCLE

CREATE SEQUENCE SQ_LANCAMENTO
START WITH 1
MINVALUE 1
INCREMENT BY 1
NO MAXVALUE
NO CACHE
NOCYCLE